<?php

/**
 * @file
 * Test module for the Simple LDAP module.
 *
 * To be used if custom module hooks need to be tested.
 */

/**
 * Reusable function to set up the server settings.
 */
function simple_ldap_test_setup() {
  // Include the file that contains the server configuration.
  $path = DRUPAL_ROOT . '/' . drupal_get_path('module', 'simple_ldap_test');
  $file = $path . "/simple_ldap_test.config.inc";
  if (is_file($file)) {
    include $file;
  }

  // Add fields to the user entity.
  $map = simple_ldap_user_map();
  foreach ($map as $attribute) {
    if ($attribute['type'] == 'field') {
      $field = field_create_field(array(
        'field_name' => $attribute['drupal'],
        'type' => 'text',
        'cardinality' => 1,
      ));
      $instance = field_create_instance(array(
        'field_name' => $attribute['drupal'],
        'entity_type' => 'user',
        'label' => $attribute['drupal'],
        'bundle' => 'user',
        'required' => $attribute['required'],
        'settings' => array(
          'user_register_form' => $attribute['required'],
        ),
      ));
    }
  }

}
