<?php

/**
 * @file
 * Install, update and uninstall functions for the simple_ldap_test module.
 */

/**
 * Implements hook_install().
 */
function simple_ldap_test_install() {
  // Include the file that contains the server configuration.
  $path = DRUPAL_ROOT . '/' . drupal_get_path('module', 'simple_ldap_test');
  $file = $path . "/simple_ldap_test.config.inc";
  if (is_file($file)) {
    include $file;
  }

  // Add fields to the user entity.
  if (function_exists('simple_ldap_user_attribute_map')) {
    $server = SimpleLdapServer::singleton();
    $objectclass = variable_get('simple_ldap_user_objectclass');
    $must = $server->schema->must($objectclass, TRUE);
    $attribute_map = simple_ldap_user_attribute_map();
    foreach ($attribute_map as $attribute) {
      if ($attribute['type'] == 'field') {
        $required = in_array($attribute['ldap'], $must);
        field_create_field(array(
          'field_name' => $attribute['drupal'],
          'type' => 'text',
          'cardinality' => 1,
        ));
        field_create_instance(array(
          'field_name' => $attribute['drupal'],
          'entity_type' => 'user',
          'label' => $attribute['drupal'],
          'bundle' => 'user',
          'required' => $required,
          'settings' => array(
            'user_register_form' => $required,
          ),
        ));
      }
    }
  }
}
