<?php

/**
 * @file
 * Install, update and uninstall functions for the simple_ldap_test module.
 */

/**
 * Implements hook_install().
 */
function simple_ldap_test_install() {
  // Include the file that contains the server configuration.
  $path = DRUPAL_ROOT . '/' . drupal_get_path('module', 'simple_ldap_test');
  $file = $path . "/simple_ldap_test.config.inc";
  if (is_file($file)) {
    include $file;
  }

  // Add fields to the user entity.
  if (function_exists('simple_ldap_user_attribute_map')) {
    $server = SimpleLdapServer::singleton();
    $objectclass = variable_get('simple_ldap_user_objectclass');
    $must = array();
    foreach ($objectclass as $o) {
      $must += $server->schema->must($o, TRUE);
    }
    $attribute_map = simple_ldap_user_attribute_map();
    foreach ($attribute_map as $attribute) {

      // Skip drupal-to-ldap many-to-one mappings.
      if (count($attribute['drupal']) > 1) {
        break;
      }

      // Get the drupal name and type.
      $drupal_attribute = reset($attribute['drupal']);
      $type = substr($drupal_attribute, 0, 1);

      // Create user fields.
      if ($type == '#') {
        $drupal_attribute = substr($drupal_attribute, 1);
        $required = in_array($attribute['ldap'], $must);
        field_create_field(array(
          'field_name' => $drupal_attribute,
          'type' => 'text',
          'cardinality' => 1,
        ));
        field_create_instance(array(
          'field_name' => $drupal_attribute,
          'entity_type' => 'user',
          'label' => $drupal_attribute,
          'bundle' => 'user',
          'required' => $required,
          'settings' => array(
            'user_register_form' => $required,
          ),
        ));
      }
    }
  }
}
