<?php
/**
 * @file
 * simple_ldap module installation.
 */

/**
 * Implements hook_uninstall().
 */
function simple_ldap_uninstall() {
  variable_del('simple_ldap_host');
  variable_del('simple_ldap_port');
  variable_del('simple_ldap_starttls');
  variable_del('simple_ldap_binddn');
  variable_del('simple_ldap_bindpw');
  variable_del('simple_ldap_readonly');
  variable_del('simple_ldap_pagesize');
}
