<?php
/**
 * @file
 * Main simple_ldap module file.
 */

// Include the simple_ldap class files.
module_load_include('php', 'simple_ldap', 'SimpleLdapSchema.class');
module_load_include('php', 'simple_ldap', 'SimpleLdapServer.class');

/**
 * Implements hook_menu().
 */
function simple_ldap_menu() {
  $items = array();

  $items['admin/config/people/simple_ldap'] = array(
    'title' => 'Simple LDAP Configuration',
    'description' => 'LDAP server, authentication parameters, roles, provisioning, etc.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('simple_ldap_admin'),
    'access arguments' => array('administer site configurations'),
    'file' => 'simple_ldap.admin.inc',
  );

  $items['admin/config/people/simple_ldap/server'] = array(
    'title' => 'Server',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );

  return $items;
}
