<?php
/**
 * @file
 * Main simple_ldap_user module file.
 */

/**
 * Implements hook_menu().
 */
function simple_ldap_user_menu() {
  $items = array();

  $items['admin/config/people/simple_ldap/user'] = array(
    'title' => 'Users',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('simple_ldap_user_admin'),
    'access arguments' => array('administer site configuration'),
    'file' => 'simple_ldap_user.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 1,
  );

  return $items;
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Overrides the built-in user module's list of users, setting accounts to
 * "blocked" if there is no matching LDAP account.
 */
function simple_ldap_user_form_user_admin_account_alter(&$form, &$form_state, $form_id) {
  // Update the user array.
  foreach ($form['accounts']['#options'] as $uid => $user) {

    // Don't mess with user/1.
    if ($uid == 1) {
      continue;
    }

    // Verify active users. Blocked users may be provisioned to LDAP when they
    // are set to active, so they are left alone here.
    if ($user['status'] == 'active') {
      // Load the Drupal user object.
      $drupal_user = user_load($uid);

      // Check whether the user exists in LDAP.
      $ldap_user = SimpleLdapUser::singleton($drupal_user->name);
      if (!$ldap_user->exists()) {
        $form['accounts']['#options'][$uid]['status'] = 'blocked';
      }
    }
  }
}

/**
 * Implements hook_entity_info_alter().
 *
 * Specifies that SimpleLdapuserController should be used to load users instead
 * of the default controller.
 */
function simple_ldap_user_entity_info_alter(&$entity_info) {
  if (isset($entity_info['user'])) {
    // Use the SimpleLdapUserController class to manage users.
    $entity_info['user']['controller class'] = 'SimpleLdapUserController';
  }
}

/**
 * Implements hook_form_alter().
 *
 * @TODO It would be better to use hook_user_login() which works
 * even if the login is not coming from a form submission.
 */
function simple_ldap_user_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
    case 'user_login_block':
      // Remove the register and password reminder links.
      unset($form['links']);
    case 'user_login':
      $validate = array();
      foreach ($form['#validate'] as $callback) {
        if ($callback == 'user_login_final_validate') {
          $validate[] = 'simple_ldap_user_login_authenticate_validate';
        }
        $validate[] = $callback;
      }
      $form['#validate'] = $validate;
      break;

    default:
  }
}

/**
 * Implements hook_menu_alter().
 *
 * Disables the user register and password reminder pages if the LDAP server is
 * read-only.
 */
function simple_ldap_user_menu_alter(&$items) {
  $server = SimpleLdapServer::singleton();
  if ($server->readonly) {
    unset($items['user/register']);
    unset($items['user/password']);
  }
}

/**
 * Validate a user login form against the LDAP directory.
 */
function simple_ldap_user_login_authenticate_validate($form, &$form_state) {
  // Check if the user has already been validated as user 1.
  if (isset($form_state['uid']) && $form_state['uid'] == 1) {
    return;
  }

  // Reset validation for all other users.
  unset($form_state['uid']);

  // Only attempt validation if both a username and password are present.
  $name = trim($form_state['values']['name']);
  $pass = trim($form_state['values']['pass']);
  if (!empty($name) && !empty($pass)) {

    // Authenticate the credentials against the LDAP directory.
    $ldap_user = SimpleLdapUser::singleton($name);
    if ($ldap_user->authenticate($pass)) {

      // Attempt to load the drupal user, if it exists.
      $drupal_user = user_load_by_name($name);

      // Create a new user object if one did not exist.
      if (empty($drupal_user)) {
        $attribute_name = variable_get('simple_ldap_user_attribute_name');
        $account = array(
          'name' => $ldap_user->$attribute_name,
          'status' => 1,
        );
        $drupal_user = user_save(NULL, $account);
      }

      // Set the form uid to indicate that the user is authenticated.
      $form_state['uid'] = $drupal_user->uid;
    }

  }
}

/**
 * Returns whether simple_ldap_user has been configured.
 */
function simple_ldap_user_configured() {
  $configured = TRUE;

  // Check each of the required configuration items.
  $configured = $configured && variable_get('simple_ldap_user_basedn') !== NULL;
  $configured = $configured && variable_get('simple_ldap_user_scope') !== NULL;
  $configured = $configured && variable_get('simple_ldap_user_objectclass') !== NULL;
  $configured = $configured && variable_get('simple_ldap_user_attribute_name') !== NULL;
  $configured = $configured && variable_get('simple_ldap_user_attribute_mail') !== NULL;

  return $configured;
}
