<?php
/**
 * @file
 * Main simple_ldap_role module file.
 */

/**
 * Implements hook_menu().
 */
function simple_ldap_role_menu() {
  $items = array();

  $items['admin/config/people/simple_ldap/role'] = array(
    'title' => 'Roles',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('simple_ldap_role_admin'),
    'access arguments' => array('adminster site configuration'),
    'file' => 'simple_ldap_role.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 2,
  );

  return $items;
}

/**
 * Implements hook_user_load().
 *
 * Override the roles based on what is in the LDAP directory.
 *
 * @todo  check for DRUPAL_AUTHENTICATED_RID and DRUPAL_ANONYMOUS_RID.
 */
function simple_ldap_role_user_load($users) {
}

/**
 * Implements hook_user_role_presave().
 *
 * Fires before a role is added or edited.
 *
 * @todo simple_ldap_role_user_role_presave()
 */
function simple_ldap_role_user_role_presave($role) {
}

/**
 * Implements hook_user_role_insert().
 *
 * Fires when a role is inserted.
 *
 * @todo simple_ldap_role_user_role_insert()
 */
function simple_ldap_role_user_role_insert($role) {
}

/**
 * Implements hook_user_role_update().
 *
 * Fires when a role is updated.
 *
 * @todo simple_ldap_role_user_role_update()
 */
function simple_ldap_role_user_role_update($role) {
}

/**
 * Implements hook_user_role_delete().
 *
 * Fires when a role is deleted.
 *
 * @todo simple_ldap_role_user_role_delete()
 */
function simple_ldap_role_user_role_delete($role) {
}

/**
 * Returns the configured authoritative data source.
 *
 * This value depends on both the configurations of simple_ldap and
 * simple_ldap_role.
 */
function simple_ldap_role_source() {
  $server = SimpleLdapServer::singleton();

  // If the LDAP server is set to read-only, force ldap as the source.
  if ($server->readonly) {
    return 'ldap';
  }

  // Get the source config from simple_ldap_role.
  return variable_get('simple_ldap_role_source', 'ldap');
}

/**
 * Returns the Simple LDAP Role attribute map, if configured.
 */
function simple_ldap_role_attribute_map() {
  $attribute_map = variable_get('simple_ldap_role_attribute_map', array());
  foreach ($attribute_map as $key => $attribute) {
    // LDAP likese lowercase.
    $attribute_map[$key]['ldap'] = strtolower($attribute_map[$key]['ldap']);

    // Make sure a type is set.
    if (!isset($attribute['type'])) {
      $attribute_map[$key]['type'] = 'default';
    }

    // Make sure "required" is set.
    if (!isset($attribute['required'])) {
      $attribute_map[$key]['required'] = FALSE;
    }
  }
  return $attribute_map;
}
