<?php

/**
 * @file
 * Simple LDAP SSO install/update hooks.
 */

/**
 * Implements hook_uninstall().
 */
function simple_ldap_sso_uninstall() {
  variable_del('simple_ldap_sso_binddn');
  variable_del('simple_ldap_sso_bindpw');
  variable_del('simple_ldap_sso_encryption_key');
  variable_del('simple_ldap_sso_attribute_sid');
  variable_del('simple_ldap_sso_hashing_algorithm');
  variable_del('simple_ldap_sso_flood_limit');
  variable_del('simple_ldap_sso_flood_window');
}
